#!/usr/bin/env bash
# This script displays the content of the file /etc/passwd

filename='/etc/passwd'
while IFS=":" read -r user pwd uid gid uid_info home cmd
do
	echo "The user $user is part of the $gid gang,"\
		"lives in $home and rides $cmd."\
		"$uid's place is protected by the passcode $pwd,"\
		"more info about the user here: $uid_info"

done < $filename
